-- 산술 연산자

SELECT ename, sal, SAL * 1.1 -- 급여 10% 인상분
FROM T_EMP;

SELECT ENAME ,SAL ,COMM 
FROM T_EMP ;

SELECT ename, sal, comm, sal + COMM -- null 값과의 산술연산은 무.조.건 NULL!!
FROM T_EMP ;



-- WHERE 조건절

SELECT * FROM T_EMP WHERE job='SALESMAN' ;
SELECT * FROM T_EMP WHERE job='SALESMAn' ; -- 문자열은 대소문자 구분!

-- p13
SELECT ENAME, sal, deptno
FROM T_EMP 
WHERE DEPTNO = 10;

SELECT ENAME ,SAL 
FROM T_EMP 
WHERE sal >2000;


SELECT ENAME ,EMPNO ,SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT';

-- 연습
-- 학생 테이블에서
-- 2,3 학년(grade) 학생의 이름(name), 학년(grade) 출력

SELECT NAME, GRADE 
FROM T_STUDENT
WHERE GRADE = 2 OR GRADE = 3;

SELECT NAME, GRADE 
FROM T_STUDENT
WHERE GRADE IN (2,3);

SELECT NAME, GRADE 
FROM T_STUDENT
WHERE GRADE > 1 AND GRADE < 4;

SELECT NAME, GRADE 
FROM T_STUDENT
WHERE GRADE NOT IN (1, 4);

SELECT NAME, GRADE 
FROM T_STUDENT
WHERE GRADE BETWEEN 2 AND 3;

SELECT NAME ,PAY , POSITION 
FROM T_PROFESSOR 
WHERE PAY >300 AND "POSITION" = '정교수';

SELECT NAME , POSITION
FROM T_PROFESSOR
WHERE BONUS IS NULL ;

-- LIKE

SELECT NAME 
FROM T_PROFESSOR 
WHERE NAME LIKE '김%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%NE%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '_A';


INSERT INTO T_STUDENT VALUES(9091,'김수진','sooplus',2 ,101 ,1004 );

DELETE FROM T_STUDENT WHERE GRADE =4;

SELECT * FROM T_STUDENT ;



CREATE OR REPLACE VIEW  v_stud_info ("학생이름","학생학과명","담당교수님 이름")
AS
SELECT s.NAME,d.DNAME ,p.NAME FROM T_STUDENT s,T_DEPARTMENT d,T_PROFESSOR p WHERE s.DEPTNO1 = d.DEPTNO AND s.PROFNO = p.PROFNO AND d.DEPTNO = p.DEPTNO ;


SELECT * FROM v_stud_info;
SELECT * FROM T_STUDENT ;

SELECT * FROM T_PROFESSOR ;
SELECT * FROM T_DEPARTMENT ;
COMMIT;

ALTER TABLE T_PROFESSOR ADD BIRTHDAY DATE;
ALTER TABLE T_STUDENT DELETE birthday DATE;











