-- 묵시적 자동 형변환 예
SELECT 1+1 FROM DUAL ;  -- 2
SELECT '1' +1 FROM DUAL ;  -- 2

SELECT TO_NUMBER('1') + 1 FROM DUAL ;

-- TO_CHAR 함수 (날짜 - > 문자)

SELECT SYSDATE,
		TO_CHAR(SYSDATE,'YYYY' ) 연도4자리,
		TO_CHAR(SYSDATE,'RRRR' ) 연도Y2K버그이후,
		TO_CHAR(SYSDATE,'YY' ) 연도2자리,
		TO_CHAR(SYSDATE,'YEAR' ) 연도영문
FROM DUAL ;

SELECT  TO_CHAR(Sysdate, 'DD') 일숫자2자리,
		TO_CHAR(Sysdate, 'DDTH') 몇번째날,
		TO_CHAR(Sysdate, 'DAY') 요일,
		TO_CHAR(SYSDATE, 'Dy' ) 요일앞자리 
FROM DUAL ;

SELECT 
	TO_CHAR(SYSDATE, 'MM') 월2자리,
	TO_CHAR(SYSDATE, 'MON') 월3자리,  -- 7월
	TO_CHAR(SYSDATE, 'MONTH','NLS_DATE_LANGUAGE=KOREAN')  월전체,  -- 7월
	TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE=KOREAN') 월영문3자리,  -- JUL
	TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(대)", -- JULY
	TO_CHAR(SYSDATE, 'month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(소)",  -- july
	TO_CHAR(SYSDATE, 'Month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(첫글자대)" -- July
FROM DUAL 


SELECT 
	TO_CHAR(SYSDATE, 'HH24') 시24hr,
	TO_CHAR(SYSDATE, 'HH')  시12hr,
	TO_CHAR(SYSDATE, 'MI') 분,
	TO_CHAR(SYSDATE, 'SS') 초,
	TO_CHAR(SYSDATE, 'HH:MI:SS' ) 
FROM dual;
-- #4301
SELECT 
	TO_CHAR(SYSDATE,'RR/MM/DD' ) "SYSDATE",
	TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS' ) 날짜 
FROM DUAL ;


-- #4302
SELECT NAME ,TO_CHAR(BIRTHDAY ,'YYYY-MM-DD') 생일
FROM T_STUDENT 
WHERE TO_CHAR(BIRTHDAY ,'MM') = '03'; 

-- TO_CHAR : 대소문자 지정예
SELECT
SYSDATE,
TO_CHAR(SYSDATE, 'Dy Month DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A1,
TO_CHAR(SYSDATE, 'dy month dd, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A2,
TO_CHAR(SYSDATE, 'DY MONTH DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A3
FROM DUAL


-- TO_CHAR() 함수 - 숫자를 문자로 변환
SELECT
	1234,
	TO_CHAR(1234, '99999') "9하나당 1자리" ,
	TO_CHAR(1234, '099999') "빈자리 0으로" ,
	TO_CHAR(1234, '$9999') "빈자리 $로",
	TO_CHAR(1234.1264,'9999.99' )"소수점이하2자리", 
	TO_CHAR(123456789, '999,999,999') "천단위의 구분기호"
FROM DUAL ;

-- #4303
SELECT NAME , TO_CHAR(NVL2(BONUS ,PAY *12 +BONUS ,PAY *12),'9,999') 연봉 
FROM T_PROFESSOR 
WHERE DEPTNO = 101;

-- TO_NUMBER() 함수 - 숫자로 변환
SELECT TO_NUMBER('123.44') FROM DUAL ;

-- TO_DATE() 함수  : 문자->날짜로 변환
SELECT 
	TO_DATE('2019-02-28','YYYY-MM-DD') TO_DATE
FROM DUAL ;

-- #4304
SELECT NAME ,HIREDATE 입사일 , TO_CHAR(PAY *12 ,'99,999') 연봉, TO_CHAR((PAY *12 )*1.1   ,'99,999') 인상후
FROM T_PROFESSOR 
WHERE Hiredate < TO_DATE('2000-01-01','YYYY-MM-DD');
