SELECT * FROM TEST_MEMBER ;

--INSERT INTO 테이블 이름 
--DELETE FROM 테이블 이름
--UPDATE 테이블 이름 SET

INSERT INTO TEST_MEMBER values(10,'이성준',sysdate);

SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES(22, '이승환', '21-FEB-94');
INSERT INTO TEST_MEMBER VALUES(17,'윤종섭','03-AUG-19');
INSERT INTO TEST_MEMBER VALUES('','이예지',''); -- 비어있는 '' 를 INSERT 하면 NULL값 처리
--INSERT INTO TEST_MEMBER VALUES(10,'',sysdate);
INSERT INTO TEST_MEMBER VALUES(NULL,'문상현','01-jan-17');

--dBeaver 에서는 기본적으로 auto-commit 수행

SELECT * FROM TEST_MEMBER ORDER BY MB_NO DESC;



